# frozen_string_literal: true

RESET = "\e[0m"
BOLD = "\e[1m"
FAINT = "\e[2m"
ITALIC = "\e[3m"
UNDERLINE = "\e[4m"
SLOW_BLINK = "\e[5m"
RAPID_BLINK = "\e[6m"
CROSS_OUT = "\e[9m"
DOUBLE_UNDERLINE = "\e[21m"
RESET_BOLD = "\e[22m"
RESET_ITALIC_UNDERLINE = "\e[23m"
RESET_BLINK = "\e[25m"

# Text colors
BLACK = "\e[30m"
RED = "\e[31m"
GREEN = "\e[32m"
YELLOW = "\e[33m"
BLUE = "\e[34m"
MAGENTA = "\e[35m"
CYAN = "\e[36m"
WHITE = "\e[37m"
DEFAULT_COLOR = "\e[39m"

# Background colors
BLACK_BG = "\e[40m"
RED_BG = "\e[41m"
GREEN_BG = "\e[42m"
YELLOW_BG = "\e[43m"
BLUE_BG = "\e[44m"
MAGENTA_BG = "\e[45m"
CYAN_BG = "\e[46m"
WHITE_BG = "\e[47m"
DEFAULT_BG = "\e[49m"

# Text color intensity
BRIGHT_BLACK = "\e[90m"
BRIGHT_RED = "\e[91m"
BRIGHT_GREEN = "\e[92m"
BRIGHT_YELLOW = "\e[93m"
BRIGHT_BLUE = "\e[94m"
BRIGHT_MAGENTA = "\e[95m"
BRIGHT_CYAN = "\e[96m"
BRIGHT_WHITE = "\e[97m"

# Background color intensity
BRIGHT_BLACK_BG = "\e[100m"
BRIGHT_RED_BG = "\e[101m"
BRIGHT_GREEN_BG = "\e[102m"
BRIGHT_YELLOW_BG = "\e[103m"
BRIGHT_BLUE_BG = "\e[104m"
BRIGHT_MAGENTA_BG = "\e[105m"
BRIGHT_CYAN_BG = "\e[106m"
BRIGHT_WHITE_BG = "\e[107m"
